version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Berlin"
      
  # Dependencies update for ci
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Berlin"
