# action.yml
name: "bosh-compiler"
description: "Compiles a bosh release without using a director"

inputs:
  file:
    description: "Location of the file to compile"
    required: true
  args:
    description: "Args to pass to the bc command"
    required: true
    default: '--guess'

runs:
  using: "docker"
  image: "docker://ghcr.io/cloudfoundry/bosh-compile-action:main"
