name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    env:
      GO_VERSION: 1.16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          args: --config .golangci.yaml
