name: Integation Tests

on:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Build Go
      run: make linux

    - name: Build Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: cloudfoundry/bc:latest
        push: false

    - name: Run Tests
      run: |
        go get github.com/onsi/ginkgo/ginkgo 
        make e2e
